language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: natalie-garate-test
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: 28o1eb5O+B+6SNlOOFERZpFI4Udpwdf4ObdCvxFeMKDVbasCuI6TNXI8k+LVQZ6r0TBbmYxxj4oWjjuL/NErquHV1vGVcoC2LPIbjCvleUNqlZM7/RQMUKFWOJ3wKyHAtcVYUZzjR+gcg6vEGOPPSAirQdwlOC/LDBeiwF+N9r2GwWmYelMsGYFPfZtv8IqcHzYMbv89NFNEhKvqejOMTa8SaDO/VeMNgIuVvP+/dtw8fy+LzdLyFoTHqGJC5j+6mSp5OlYLtgGlll5lrDmtR78lLUuGa6wh3QkVl2j9cnGyASvtNmdYrdGygUMNUypJXTZp5TSO0WEZqUlzPtj7wK7OnVvpy24/zyiiYuipvWe35e9UrS9mLatL8TL31URF/+uyx6nhAwa9oAF4F6Jmw5pK8VIaYN6R6eZbcQECTnQ/4iLq3d/wz9v5jNEgJRBdNrm/kRsy9LA/ybSYmk2tdggjum48YzlsCQE1J4o3TCTU9PENFVrkXm1SkXPBPQ/DWMCXI/cOeWF4RHcHkZmO2/QE6I86s7Aan8or9/+E2Ow/6axWxqaixk/WKUm7uhT9madbj7BbP1soWE/Ae4gvZvTOD2N2//zEVs9qksgNM7TEdNP5Hk7MbZNFSrL8ceIItbVCuNGq/OXfnWag6gweCfqQSNeHPkmJsvIRnHDaCh8=
